CREATE TABLE "Users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                            "username" varchar UNIQUE,
                                                                                               "hash" varchar, "name" varchar, "email" varchar UNIQUE,
                                                                                                                                               "created_at" timestamp,
                                                                                                                                                            "updated_at" timestamp);


CREATE TABLE "Performers" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                                 "user_id" integer, "name" varchar, "pronouns" varchar, "summary" varchar, "description" varchar, "url" varchar, "facebook_url" varchar, "instagram_url" varchar, "profile_image" varchar, "image1" varchar, "image2" varchar, "image3" varchar, "image4" varchar, "image5" varchar, "image6" varchar, "created_at" timestamp,
                                                                                                                                                                                                                                                                                                                                                                                                    "updated_at" timestamp);


CREATE TABLE "Events" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                             "title" varchar, "decription" varchar, "address" varchar, "city" varchar, "image" varchar, "url" varchar, "facebook_url" varchar, "instagram_url" varchar, "price" integer, "date" timestamp,
                                                                                                                                                                                                                                                                "time" timestamp,
                                                                                                                                                                                                                                                                       "created_by" integer, "created_at" timestamp,
                                                                                                                                                                                                                                                                                                          "updated_at" timestamp);


CREATE TABLE "PerformerEvents" ("event_id" integer, "performer_id" integer);


ALTER TABLE "Events" ADD
FOREIGN KEY ("created_by") REFERENCES "Users" ("id");


ALTER TABLE "PerformerEvents" ADD
FOREIGN KEY ("performer_id") REFERENCES "Performers" ("id");


ALTER TABLE "PerformerEvents" ADD
FOREIGN KEY ("event_id") REFERENCES "Events" ("id");

