CREATE TABLE "Users" ("id" varchar PRIMARY KEY,
                                           "first_name" varchar UNIQUE,
                                                                "last_name" varchar, "username" varchar, "email" varchar UNIQUE);


CREATE TABLE "Performers" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                                 "user_id" varchar, "name" varchar, "pronouns" varchar, "summary" varchar, "description" varchar, "url" varchar, "facebook_url" varchar, "instagram_url" varchar, "profile_image" varchar, "image1" varchar, "image2" varchar, "image3" varchar, "image4" varchar, "image5" varchar, "image6" varchar);


CREATE TABLE "Events" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                             "title" varchar, "decription" varchar, "venue" varchar, "address" varchar, "city" varchar, "country" varchar, "image" varchar, "url" varchar, "facebook_url" varchar, "instagram_url" varchar, "price" integer, "date" timestamp,
                                                                                                                                                                                                                                                                                                    "time" timestamp,
                                                                                                                                                                                                                                                                                                           "created_by" varchar);


CREATE TABLE "Houses" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                             "name" varchar);


CREATE TABLE "PerformerEvents" ("event_id" integer, "performer_id" integer);


CREATE TABLE "UserHouses" ("house_id" integer, "user_id" varchar);


ALTER TABLE "Events" ADD
FOREIGN KEY ("created_by") REFERENCES "Users" ("id");


ALTER TABLE "UserHouses" ADD
FOREIGN KEY ("user_id") REFERENCES "Users" ("id");


ALTER TABLE "UserHouses" ADD
FOREIGN KEY ("house_id") REFERENCES "Houses" ("id");


ALTER TABLE "PerformerEvents" ADD
FOREIGN KEY ("performer_id") REFERENCES "Performers" ("id");


ALTER TABLE "PerformerEvents" ADD
FOREIGN KEY ("event_id") REFERENCES "Events" ("id");

